"""Animate the layout search, as documentation you can re-run.

    layout_demo.py pack test_data/small_spoon.svg test_data/medium_spoon.svg \\
        test_data/big_spoon.svg --out docs/media/pack.gif

    layout_demo.py group test_data/big_spoon.svg test_data/screwdriver.svg \\
        --start one-per-bin --out docs/media/group.gif

    layout_demo.py drawer test_data/*_spoon.svg test_data/*_fork.svg \\
        --drawer 340x260 --out docs/media/drawer.gif

Each stage runs the real search - the same functions the CLI calls, with
the same defaults - and draws every step of it through the same
`preview.LayoutShapes` that produces the printed sheet. So an animation
cannot show an algorithm other than the one that ships, or a bin other
than the one it wrote.

That is the point of it being a script rather than a recording: a GIF
checked into a repo goes stale silently, and these are regenerated by a
command anybody can run, with tests that run it too.

The three stages animate three different *kinds* of search, which is most
of what there is to see. `pack` is continuous and stochastic - parts
drift, shove each other, and fail; the bin gets bigger and they settle.
`group` is discrete and heuristic - the picture barely changes while the
search prices candidate after candidate, then jumps when one is worth
taking. `drawer` is discrete and exact - bins snap to cells, and the
search backs out of dead ends rather than drifting out of them.
"""

import argparse
import sys
from dataclasses import replace
from math import ceil, sqrt
from typing import Sequence

import numpy as np

from pipeline.gif_writer import DEFAULT_COLORS, Canvas, WriteGif
from pipeline.layout.descent import Snapshot
from pipeline.layout.drawer import (
    PLACED,
    AdmissibleFootprints,
    Assign,
    AssignmentResult,
    Drawer,
    DrawerCells,
    Trial,
)
from pipeline.layout.drawer import ParseDrawer as _ParseDrawer
from pipeline.layout.floorplan import FloorplanPages
from pipeline.layout.grouping import FirstFit, Group, Improve, OnePerBin, Step
from pipeline.layout.loading import BuildParts, ReadContours
from pipeline.layout.packer import Pack
from pipeline.layout.parameters import QUARTER_TURNS, ROTATIONS, FromOverrides, LayoutParameters
from pipeline.layout.part import Part
from pipeline.layout.placement import Layout
from pipeline.layout.render import Bordered, InRows, RenderLayout, RenderShapes, SideBySide

# Half the screen preview's scale. A 4x2 bin comes out around 340px wide,
# which is legible inline in a README and keeps a few hundred frames inside
# a few hundred kilobytes - the size at which a GIF is worth committing.
DEFAULT_PIXELS_PER_MM = 2.0

# A drawer is several bins across, so the same scale would produce an image
# too wide to embed. Coarser here, and the subject is where a bin sits
# rather than the shape of the spoon in it.
DEFAULT_DRAWER_PIXELS_PER_MM = 0.8

# The solver takes hundreds of small steps, and consecutive ones differ by
# less than a rendered pixel. Sampling loses nothing visible and divides
# both the file size and the time spent drawing.
DEFAULT_EVERY = 3

DEFAULT_MS_PER_FRAME = 60

# Frames held on the finished result, so an animation ends on the answer
# instead of flicking straight back to a scattered start.
DEFAULT_HOLD = 20

# Past this the GIF is too big to embed, and the excess is the middle of a
# long search rather than anything a viewer needs. Truncation is reported,
# never silent.
DEFAULT_MAX_FRAMES = 400

# Several bins across, and they are the subject rather than their
# arrangement, so coarser than a single bin and finer than a drawer.
DEFAULT_GROUP_PIXELS_PER_MM = 1.2

# Blank millimeters between drawers on a multi-drawer frame, so two drawer
# edges do not read as one shared wall.
DRAWER_GAP_MM = 6.0

# The same, between bins, and small on purpose: every rendered page already
# carries `render.MARGIN_MM` of white on each side, so this is on top of 4mm
# that is there whatever happens. Two adjacent marked bins stay legible even
# at zero, since each one's own rim is drawn inside its mark.
BIN_GAP_MM = 3.0


class Recording:
    """Frames kept from a search, sampled and capped.

    Counts steps rather than frames when sampling, so the interval is in
    search steps - the thing that is actually uniform - instead of in
    whatever survived the last cap.
    """

    def __init__(self, every: int = DEFAULT_EVERY, max_frames: int = DEFAULT_MAX_FRAMES):
        if every < 1:
            raise ValueError(f"sample at least every step, got every={every}")

        self._every = every

        # The cap applies to recorded frames only. Frames appended by hand
        # afterwards - the hold on the final result - are the caller's, and
        # a truncated recording is exactly when ending on the answer matters
        # most.
        self.cap = max_frames

        self.frames: list[np.ndarray] = []
        self.steps = 0
        self.truncated = False

    def Wants(self) -> bool:
        """Count this step, and say whether it should be drawn.

        Drawing a frame costs far more than the search step that produced
        it, so the sampling decision is made before anything is rendered.
        """
        self.steps += 1
        if self.steps % self._every:
            return False
        if len(self.frames) >= self.cap:
            self.truncated = True
            return False
        return True


class PackRecorder(Recording):
    """The arrangement search: one frame per sampled solver iteration.

    Draws through `RenderLayout`, so a frame is the printed sheet at screen
    scale rather than a second drawing of the same arrangement.
    """

    def __init__(
        self,
        parts: dict[int, Part],
        params: LayoutParameters,
        pixels_per_mm: float = DEFAULT_PIXELS_PER_MM,
        every: int = DEFAULT_EVERY,
        max_frames: int = DEFAULT_MAX_FRAMES,
    ):
        super().__init__(every, max_frames)
        self._parts = parts
        self._params = params
        self._pixels_per_mm = pixels_per_mm

    def __call__(self, snapshot: Snapshot) -> None:
        if self.Wants():
            self.Draw(Layout(grid=snapshot.grid, placements=snapshot.placements, inset=self._params.inset))

    def Draw(self, layout: Layout) -> None:
        """Append one layout as a frame, whether or not it came from a
        snapshot - which is how the finished layout gets held at the end.
        """
        self.frames.append(RenderLayout(layout, self._parts, self._pixels_per_mm))


class DrawerRecorder(Recording):
    """The assignment search: one frame per sampled partial assignment.

    Draws through `floorplan.FloorplanPages`, so a frame is the sheet you
    would print and lay in the drawer. All the drawers go side by side in
    one image, because bins move between them and two separate animations
    could not show that.
    """

    def __init__(
        self,
        drawers: Sequence[Drawer],
        layouts: dict[int, Layout],
        parts: dict[int, Part],
        pixels_per_mm: float = DEFAULT_DRAWER_PIXELS_PER_MM,
        every: int = DEFAULT_EVERY,
        max_frames: int = DEFAULT_MAX_FRAMES,
    ):
        super().__init__(every, max_frames)
        self._drawers = drawers
        self._layouts = layouts
        self._parts = parts
        self._pixels_per_mm = pixels_per_mm

    def __call__(self, trial: Trial) -> None:
        if self.Wants():
            # The outcome is not known mid-search and is not drawn anyway;
            # the floorplan reads `slots` and nothing else.
            self.Draw(AssignmentResult(PLACED, {slot.bin_id: slot for slot in trial.slots}))

    def Draw(self, result: AssignmentResult) -> None:
        pages = FloorplanPages(self._drawers, self._layouts, result, self._parts)
        images = [RenderShapes(page.shapes, page.width, page.height, self._pixels_per_mm) for page in pages]
        self.frames.append(SideBySide(images, gap=int(round(DRAWER_GAP_MM * self._pixels_per_mm))))


class GroupRecorder(Recording):
    """The grouping search: one frame per sampled candidate.

    Every bin is drawn, side by side, and the ones the search is currently
    asking about get a border. That border is most of the value here: the
    picture only *changes* on the rare accepted move, so an animation of
    the arrangement alone would be a slideshow of five pictures with no
    hint of the hundreds of candidates priced in between.
    """

    def __init__(
        self,
        parts: dict[int, Part],
        columns: int,
        pixels_per_mm: float = DEFAULT_GROUP_PIXELS_PER_MM,
        every: int = DEFAULT_EVERY,
        max_frames: int = DEFAULT_MAX_FRAMES,
    ):
        super().__init__(every, max_frames)
        self._parts = parts
        self._pixels_per_mm = pixels_per_mm

        # Fixed for the whole animation rather than derived per frame. Bins
        # disappear as the search merges them, and a column count that
        # followed the current bin count would reflow the survivors into
        # different rows every time one went - motion that says nothing
        # about the search.
        self._columns = columns

    def __call__(self, step: Step) -> None:
        if self.Wants():
            self.Draw(step.bins, step.asking)

    def Draw(self, bins: Sequence[Layout], asking: frozenset[int] = frozenset()) -> None:
        images = []
        for index, layout in enumerate(bins):
            image = RenderLayout(layout, self._parts, self._pixels_per_mm)
            images.append(Bordered(image) if index in asking else image)
        self.frames.append(InRows(images, self._columns, gap=int(round(BIN_GAP_MM * self._pixels_per_mm))))


def ParametersFrom(args: argparse.Namespace) -> LayoutParameters:
    """The tuned defaults, with only the flags actually passed applied -
    the same `parameters.FromOverrides` rule `layout_cli` uses, so a demo
    and a real run of the same inputs behave identically.
    """
    return FromOverrides(max_grid=args.max_grid, seed=args.seed, restarts=args.restarts, rotation=args.rotation)


def ParseDrawer(text: str) -> Drawer:
    """A `WIDTHxHEIGHT` drawer interior in millimeters, as whole cells.

    The parsing itself lives in `drawer.ParseDrawer`, because the window
    needs the same thing and a drawer typed into one front end has to come
    out the same number of cells as the same drawer passed to the other.
    All this adds is argparse's exception type, which is what turns a bad
    flag into a usage message rather than a traceback.
    """
    try:
        return _ParseDrawer(text)
    except ValueError as error:
        raise argparse.ArgumentTypeError(str(error)) from None


def BuildParser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    stages = parser.add_subparsers(dest="stage", required=True, metavar="STAGE")

    pack = stages.add_parser("pack", help="parts settling into a bin, and the search stepping up a size")
    _AddSearchArguments(pack)
    pack.add_argument("--out", default="pack.gif", help="output GIF (default: pack.gif)")
    _AddAnimationArguments(pack, DEFAULT_PIXELS_PER_MM)

    group = stages.add_parser("group", help="parts moving between bins as the search prices candidates")
    _AddSearchArguments(group)
    group.add_argument("--out", default="group.gif", help="output GIF (default: group.gif)")
    group.add_argument(
        "--start",
        choices=("first-fit", "one-per-bin"),
        default="first-fit",
        help="what the local search starts from; one-per-bin gives it the most to find (default: first-fit)",
    )
    group.add_argument(
        "--columns", type=int, default=None, metavar="N", help="bins per row (default: about the square root)"
    )
    _AddAnimationArguments(group, DEFAULT_GROUP_PIXELS_PER_MM)

    drawer = stages.add_parser("drawer", help="bins packed into drawers, backtracking included")
    _AddSearchArguments(drawer)
    drawer.add_argument("--out", default="drawer.gif", help="output GIF (default: drawer.gif)")
    drawer.add_argument(
        "--drawer",
        type=ParseDrawer,
        action="append",
        metavar="WxH",
        help="a drawer's interior, in mm or as '11x9 cells'; repeat for several (default: one 500x400)",
    )
    _AddAnimationArguments(drawer, DEFAULT_DRAWER_PIXELS_PER_MM)
    return parser


def _AddSearchArguments(parser: argparse.ArgumentParser) -> None:
    """The flags that change what is searched, as opposed to how it is
    drawn.
    """
    parser.add_argument("inputs", nargs="+", metavar="FILE", help="contour dumps (.json) or SVGs to pack")
    parser.add_argument("--max-grid", type=int, default=None, help="largest grid dimension to try")
    parser.add_argument("--seed", type=int, default=None, help="search seed; a different one is a different attempt")
    parser.add_argument("--restarts", type=int, default=None, help="attempts per grid size before moving up")
    parser.add_argument(
        "--rotation",
        choices=ROTATIONS,
        default=None,
        help=f"how freely parts may turn in a bin (default: {QUARTER_TURNS})",
    )


def _AddAnimationArguments(parser: argparse.ArgumentParser, pixels_per_mm: float) -> None:
    """The flags every stage's animation shares, so they cannot drift apart
    as stages are added.
    """
    parser.add_argument(
        "--every",
        type=int,
        default=DEFAULT_EVERY,
        metavar="N",
        help=f"keep one frame per N steps (default: {DEFAULT_EVERY})",
    )
    parser.add_argument(
        "--pixels-per-mm",
        type=float,
        default=pixels_per_mm,
        metavar="P",
        help=f"render scale (default: {pixels_per_mm})",
    )
    parser.add_argument(
        "--ms-per-frame", type=int, default=DEFAULT_MS_PER_FRAME, metavar="MS", help="how long each frame is shown"
    )
    parser.add_argument(
        "--hold", type=int, default=DEFAULT_HOLD, metavar="N", help="frames to hold on the finished result"
    )
    parser.add_argument(
        "--max-frames", type=int, default=DEFAULT_MAX_FRAMES, metavar="N", help="stop recording past this many frames"
    )
    parser.add_argument(
        "--colors",
        type=int,
        default=DEFAULT_COLORS,
        metavar="N",
        help=f"palette size shared by every frame (default: {DEFAULT_COLORS})",
    )


def _Load(args: argparse.Namespace, params: LayoutParameters) -> dict[int, Part]:
    contours = ReadContours(args.inputs)
    print(f"loaded {len(contours)} contours from {len(args.inputs)} file(s)")
    return BuildParts(contours, params)


def RunPack(args: argparse.Namespace) -> int:
    params = ParametersFrom(args)
    parts = _Load(args, params)

    recorder = PackRecorder(parts, params, args.pixels_per_mm, args.every, args.max_frames)
    result = Pack(parts, params, observer=recorder)
    print(result.Report())

    if result.layout is None:
        # No frames of an answer, because there is no answer. The report
        # above already says which sizes were ruled out and how.
        return 1

    for _ in range(args.hold):
        recorder.Draw(result.layout)

    return _Write(args.out, recorder, args.ms_per_frame, args.colors)


def RunGroup(args: argparse.Namespace) -> int:
    params = ParametersFrom(args)
    parts = _Load(args, params)

    # A bin per part is the most there will ever be, so the layout is sized
    # for the opening frame and everything after it fits.
    columns = args.columns or ceil(sqrt(len(parts)))

    recorder = GroupRecorder(parts, columns, args.pixels_per_mm, args.every, args.max_frames)
    if args.start == "one-per-bin":
        # Not observed: it is one pack per part, with no search in it. Drawn
        # once so the animation opens on the baseline the search improves.
        baseline = OnePerBin(parts, params)
        print(f"starting from {len(baseline.bins)} bins, {baseline.cells} cells")
        recorder.Draw(baseline.bins)
        grouping = Improve(parts, baseline, params, observer=recorder)
    else:
        grouping = Group(parts, params, observer=recorder)

    print(grouping.Report())

    for _ in range(args.hold):
        recorder.Draw(grouping.bins)

    return _Write(args.out, recorder, args.ms_per_frame, args.colors)


def RunDrawer(args: argparse.Namespace) -> int:
    drawers = args.drawer or [DrawerCells(500.0, 400.0)]

    # Grouping is told which footprints a drawer can actually hold, which is
    # the feedback edge the architecture describes: proposing a bin no
    # drawer can store wastes the whole stack below it.
    base = ParametersFrom(args)
    params = replace(base, admissible_grids=AdmissibleFootprints(drawers, base.max_grid))

    parts = _Load(args, params)

    # First-fit rather than the full `Group`: its local search is quadratic
    # in bins with a stochastic solve per candidate, which is minutes on a
    # set this size and is not what this animation is about.
    grouping = FirstFit(parts, params)
    print(grouping.Report())

    layouts = {index: layout for index, layout in enumerate(grouping.bins)}
    footprints = {index: layout.grid for index, layout in layouts.items()}

    recorder = DrawerRecorder(drawers, layouts, parts, args.pixels_per_mm, args.every, args.max_frames)
    result = Assign(footprints, drawers, observer=recorder)
    print(result.Report(footprints))

    # Held even when the search failed: a partial assignment is the useful
    # picture of "these went in, that one did not".
    for _ in range(args.hold):
        recorder.Draw(result)

    written = _Write(args.out, recorder, args.ms_per_frame, args.colors)
    if written:
        return written
    # The GIF is written either way; the exit status reports the assignment,
    # so a script can tell "the bins did not fit" from "the demo broke".
    return 0 if result.placed else 1


def _Write(path: str, recorder: Recording, ms_per_frame: int, colors: int = DEFAULT_COLORS) -> int:
    if not recorder.frames:
        print("no frames were recorded - lower --every, or raise --max-frames")
        return 1

    WriteGif(path, recorder.frames, ms_per_frame, colors)
    if recorder.truncated:
        print(f"note: recording stopped at {recorder.cap} frames; the animation is not the whole search")

    # The canvas rather than the first frame: they differ exactly when the
    # search stepped up a bin size, which is the case worth reporting
    # honestly rather than the one to describe by its opening frame.
    height, width = Canvas(recorder.frames)
    seconds = len(recorder.frames) * ms_per_frame / 1000.0
    print(
        f"wrote {path}: {len(recorder.frames)} frames of {width}x{height}, "
        f"{seconds:.1f}s, from {recorder.steps} steps"
    )
    return 0


def Main(argv: Sequence[str] | None = None) -> int:
    args = BuildParser().parse_args(argv)
    if args.stage == "pack":
        return RunPack(args)
    if args.stage == "group":
        return RunGroup(args)
    if args.stage == "drawer":
        return RunDrawer(args)
    raise ValueError(f"unknown stage {args.stage}")  # unreachable: argparse rejects it first


if __name__ == "__main__":
    sys.exit(Main())
