"""Animate the layout search, as documentation you can re-run.

    layout_demo.py pack test_data/small_spoon.svg test_data/medium_spoon.svg \\
        test_data/big_spoon.svg --out docs/media/pack.gif

Runs the real search - the same `packer.Pack` the CLI calls, with the same
defaults - and draws every iteration of it through the same
`preview.LayoutShapes` that produces the printed sheet. So the animation
cannot show an algorithm other than the one that ships, or a bin other
than the one it wrote.

That is the point of it being a script rather than a recording: a GIF
checked into a repo goes stale silently, and this one is regenerated by a
command anybody can run, with a test that runs it too.
"""

import argparse
import sys
from typing import Sequence

import numpy as np

from pipeline.gif_writer import Canvas, WriteGif
from pipeline.layout.descent import Snapshot
from pipeline.layout.loading import BuildParts, ReadContours
from pipeline.layout.packer import Pack
from pipeline.layout.parameters import LayoutParameters
from pipeline.layout.part import Part
from pipeline.layout.placement import Layout
from pipeline.layout.render import RenderLayout

# Half the screen preview's scale. A 4x2 bin comes out around 340px wide,
# which is legible inline in a README and keeps a few hundred frames inside
# a few hundred kilobytes - the size at which a GIF is worth committing.
DEFAULT_PIXELS_PER_MM = 2.0

# The solver takes hundreds of small steps, and consecutive ones differ by
# less than a rendered pixel. Sampling loses nothing visible and divides
# both the file size and the time spent drawing.
DEFAULT_EVERY = 3

DEFAULT_MS_PER_FRAME = 60

# Frames held on the finished layout, so the animation ends on the answer
# instead of flicking straight back to a scattered start.
DEFAULT_HOLD = 20

# Past this the GIF is too big to embed, and the excess is the middle of a
# long search rather than anything a viewer needs. Truncation is reported,
# never silent.
DEFAULT_MAX_FRAMES = 400


class Recorder:
    """Renders every `every`-th snapshot the search reports.

    Draws through `RenderLayout`, so a frame is the printed sheet at screen
    scale rather than a second drawing of the same arrangement.

    Counts snapshots rather than frames when sampling, so the interval is
    in solver iterations - the thing that is actually uniform - instead of
    in whatever survived the last cap.
    """

    def __init__(
        self,
        parts: dict[int, Part],
        params: LayoutParameters,
        pixels_per_mm: float = DEFAULT_PIXELS_PER_MM,
        every: int = DEFAULT_EVERY,
        max_frames: int = DEFAULT_MAX_FRAMES,
    ):
        if every < 1:
            raise ValueError(f"sample at least every iteration, got every={every}")

        self._parts = parts
        self._params = params
        self._pixels_per_mm = pixels_per_mm
        self._every = every

        # The cap applies to recorded frames only. Frames appended by hand
        # afterwards - the hold on the final layout - are the caller's, and
        # a truncated recording is exactly when ending on the answer matters
        # most.
        self.cap = max_frames

        self.frames: list[np.ndarray] = []
        self.snapshots = 0
        self.truncated = False

    def __call__(self, snapshot: Snapshot) -> None:
        self.snapshots += 1
        if self.snapshots % self._every:
            return
        if len(self.frames) >= self.cap:
            self.truncated = True
            return
        self.Draw(Layout(grid=snapshot.grid, placements=snapshot.placements, inset=self._params.inset))

    def Draw(self, layout: Layout) -> None:
        """Append one layout as a frame, whether or not it came from a
        snapshot - which is how the finished layout gets held at the end.
        """
        self.frames.append(RenderLayout(layout, self._parts, self._pixels_per_mm))


def ParametersFrom(args: argparse.Namespace) -> LayoutParameters:
    """The tuned defaults, with only the flags actually passed applied -
    the same rule `layout_cli` follows, so a demo and a real run of the
    same inputs behave identically.
    """
    overrides = {"max_grid": args.max_grid, "seed": args.seed, "restarts": args.restarts}
    return LayoutParameters(**{name: value for name, value in overrides.items() if value is not None})


def BuildParser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    stages = parser.add_subparsers(dest="stage", required=True, metavar="STAGE")

    pack = stages.add_parser("pack", help="parts settling into a bin, and the search stepping up a size")
    pack.add_argument("inputs", nargs="+", metavar="FILE", help="contour dumps (.json) or SVGs to pack")
    pack.add_argument("--out", default="pack.gif", help="output GIF (default: pack.gif)")
    pack.add_argument("--max-grid", type=int, default=None, help="largest grid dimension to try")
    pack.add_argument("--seed", type=int, default=None, help="search seed; a different one is a different attempt")
    pack.add_argument("--restarts", type=int, default=None, help="attempts per grid size before moving up")
    _AddAnimationArguments(pack)
    return parser


def _AddAnimationArguments(parser: argparse.ArgumentParser) -> None:
    """The flags every stage's animation shares, so they cannot drift apart
    as stages are added.
    """
    parser.add_argument(
        "--every",
        type=int,
        default=DEFAULT_EVERY,
        metavar="N",
        help=f"keep one frame per N steps (default: {DEFAULT_EVERY})",
    )
    parser.add_argument("--pixels-per-mm", type=float, default=DEFAULT_PIXELS_PER_MM, metavar="P", help="render scale")
    parser.add_argument(
        "--ms-per-frame", type=int, default=DEFAULT_MS_PER_FRAME, metavar="MS", help="how long each frame is shown"
    )
    parser.add_argument(
        "--hold", type=int, default=DEFAULT_HOLD, metavar="N", help="frames to hold on the finished result"
    )
    parser.add_argument(
        "--max-frames", type=int, default=DEFAULT_MAX_FRAMES, metavar="N", help="stop recording past this many frames"
    )


def RunPack(args: argparse.Namespace) -> int:
    params = ParametersFrom(args)

    contours = ReadContours(args.inputs)
    parts = BuildParts(contours, params)
    print(f"loaded {len(contours)} contours from {len(args.inputs)} file(s)")

    recorder = Recorder(parts, params, args.pixels_per_mm, args.every, args.max_frames)
    result = Pack(parts, params, observer=recorder)
    print(result.Report())

    if result.layout is None:
        # No frames of an answer, because there is no answer. The report
        # above already says which sizes were ruled out and how.
        return 1

    for _ in range(args.hold):
        recorder.Draw(result.layout)

    return _Write(args.out, recorder, args.ms_per_frame)


def _Write(path: str, recorder: Recorder, ms_per_frame: int) -> int:
    if not recorder.frames:
        print("no frames were recorded - lower --every, or raise --max-frames")
        return 1

    WriteGif(path, recorder.frames, ms_per_frame)
    if recorder.truncated:
        print(f"note: recording stopped at {recorder.cap} frames; the animation is not the whole search")

    # The canvas rather than the first frame: they differ exactly when the
    # search stepped up a bin size, which is the case worth reporting
    # honestly rather than the one to describe by its opening frame.
    height, width = Canvas(recorder.frames)
    seconds = len(recorder.frames) * ms_per_frame / 1000.0
    print(
        f"wrote {path}: {len(recorder.frames)} frames of {width}x{height}, "
        f"{seconds:.1f}s, from {recorder.snapshots} steps"
    )
    return 0


def Main(argv: Sequence[str] | None = None) -> int:
    args = BuildParser().parse_args(argv)
    if args.stage == "pack":
        return RunPack(args)
    raise ValueError(f"unknown stage {args.stage}")  # unreachable: argparse rejects it first


if __name__ == "__main__":
    sys.exit(Main())
